### ISSUE TITLE
More of a request

### ISSUE THREAD

**Issue by GuardianGallade** [mhvuze/gmdDump#2]
This is not much of issue but more of a request. Can you upload a compiled version of this please? Thanks!

**Comment by mhvuze** [comment]
Sure! Added the binary here: https://github.com/mhvuze/gmdDump/releases/tag/1.0
Feel free to report any issues you encounter; should do what it's supposed to though.

**Comment by GuardianGallade** [comment]
So I tried opening it and I get a unhandled expression: Index was outside the bounds of the array at gmdDump.Program.Main(string[] args)

**Comment by GuardianGallade** [comment]
Never mind it works!

**Comment by GuardianGallade** [comment]
However how do I put it back int .gmd after its a .txt?

**Comment by mhvuze** [comment]
You don't, not with this tool anyway - as the name implies, it solely dumps the text ;)

**Comment by GuardianGallade** [comment]
oh okay. I asked because we are translating the great ace attorney ^^ If you want to help feel free to add me on skype with: Segabit16 i feel we could use your expertise. We have already managed to merge with the brilliant FE:Fates translation team and have a team of 20 people sadly I don't think anyone can code quite like you. So if you're up for it feel free to add me! Also, even if you not I'll be sure to give credit to you for your  amazing tool on the release thread.
